# Generated by Django 5.2.6 on 2025-09-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_skill_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='person',
        ),
    ]
