# Generated by Django 5.2.6 on 2025-09-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0005_alter_education_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
